import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    'app.title': 'Мониторинг цен на электроэнергию',
    'app.subtitle': 'Актуальные данные по всем регионам РФ',
    'app.updated': 'Обновлено',
    
    'stats.avgPrice': 'Средняя цена РФ',
    'stats.maxPrice': 'Макс. цена',
    'stats.minPrice': 'Мин. цена',
    'stats.regions': 'Регионов',
    'stats.tracked': 'отслеживается',
    'stats.perKwh': 'за кВт⋅ч',
    
    'tabs.overview': 'Обзор',
    'tabs.forecast': 'Прогноз',
    'tabs.map': 'Карта',
    'tabs.regions': 'Регионы',
    'tabs.analytics': 'Аналитика',
    'tabs.compare': 'Сравнение',
    'tabs.filters': 'Фильтры',
    
    'overview.priceDynamics': 'Динамика цен по регионам',
    'overview.avgPricesByZone': 'Средние цены по округам',
    'overview.allRegionsByChange': 'Все регионы по изменению цены',
    'overview.selectRegion': 'Выберите регион',
    
    'export.button': 'Экспорт',
    'export.excel': 'Excel (.xlsx)',
    'export.csv': 'CSV (.csv)',
    'export.csvSuccess': 'Файл CSV успешно скачан',
    'export.excelSuccess': 'Файл Excel успешно скачан',
    
    'prediction.title': 'Прогноз цен',
    'prediction.selectRegion': 'Выберите регион для прогноза',
    'prediction.subtitle': 'Прогнозирование на основе исторических данных',
    'prediction.insufficientData': 'Недостаточно данных для прогноза',
    'prediction.minDataPoints': 'Требуется минимум 10 точек данных',
    'prediction.trend': 'Тренд',
    'prediction.modelAccuracy': 'Точность модели',
    'prediction.forecastIn': 'Прогноз через',
    'prediction.days': 'дней',
    'prediction.fromCurrent': 'от текущей',
    'prediction.actual': 'Фактическая',
    'prediction.forecast': 'Прогноз',
    'prediction.today': 'Сегодня',
    'prediction.highAccuracy': 'Высокая точность',
    'prediction.mediumAccuracy': 'Средняя точность',
    'prediction.lowAccuracy': 'Низкая точность',
    'prediction.aboutTitle': 'О прогнозе:',
    'prediction.aboutText': 'Прогноз основан на линейной регрессии исторических данных. Чем дальше в будущее, тем ниже точность. Используйте прогноз как ориентир, а не абсолютное значение.',
    'prediction.risingTitle': 'Прогноз роста цен',
    'prediction.risingSubtitle': 'Регионы с вероятным повышением',
    'prediction.fallingTitle': 'Прогноз снижения цен',
    'prediction.fallingSubtitle': 'Регионы с вероятным снижением',
    'prediction.current': 'Текущая',
    'prediction.howItWorks': 'Как работает прогноз?',
    'prediction.method': 'Метод:',
    'prediction.methodText': 'Используется линейная регрессия для анализа исторических данных и выявления трендов.',
    'prediction.accuracy': 'Точность:',
    'prediction.accuracyText': 'Зависит от количества данных и стабильности цен. Прогнозы на ближайший месяц обычно более точные, чем на 3-6 месяцев вперёд.',
    'prediction.limitations': 'Ограничения:',
    'prediction.limitationsText': 'Прогноз не учитывает внешние факторы (законы, сезонность, форс-мажоры). Используйте как ориентир для планирования, а не абсолютное значение.',
    'prediction.period.oneMonth': '1 месяц',
    'prediction.period.threeMonths': '3 месяца',
    'prediction.period.sixMonths': '6 месяцев',
    'prediction.period.oneYear': '1 год',
    'prediction.period.twoYears': '2 года',
    'prediction.period.threeYears': '3 года',
    'prediction.strength': 'Сила',
    'prediction.actualPrice': 'Фактическая цена',
    'prediction.confidence.high': 'Высокая точность',
    'prediction.confidence.medium': 'Средняя точность',
    'prediction.confidence.low': 'Низкая точность',
    'prediction.veryHighAccuracy': 'Очень высокая точность',
    
    'trend.stable': 'Цены стабильны',
    'trend.risingSlightly': 'Цены незначительно растут',
    'trend.risingModerately': 'Цены умеренно растут',
    'trend.risingNoticeably': 'Цены заметно растут',
    'trend.risingSignificantly': 'Цены значительно растут',
    'trend.fallingSlightly': 'Цены незначительно снижаются',
    'trend.fallingModerately': 'Цены умеренно снижаются',
    'trend.fallingNoticeably': 'Цены заметно снижаются',
    'trend.fallingSignificantly': 'Цены значительно снижаются',
    
    'regions.all': 'Все регионы',
    'regions.of': 'из',
    'regions.search': 'Поиск региона...',
    'regions.sorting': 'Сортировка:',
    'regions.byName': 'По названию',
    'regions.byPriceAsc': 'По цене ↑',
    'regions.byPriceDesc': 'По цене ↓',
    'regions.byChangeAsc': 'По изменению ↑',
    'regions.byChangeDesc': 'По изменению ↓',
    'regions.export': 'Экспорт',
    'regions.cheaper': 'Дешевле',
    'regions.expensive': 'Дороже',
    'regions.growth': 'Рост',
    'regions.decline': 'Снижение',
    'regions.notFound': 'Регионы не найдены',
    'regions.tryAgain': 'Попробуйте изменить запрос',
    'regions.details': 'Детали региона',
    'regions.currentPrice': 'Текущая цена',
    'regions.count': 'регионов',
    
    'analytics.historicalData': 'Исторические данные цен',
    'analytics.period': 'Период:',
    'analytics.trendFor': 'Тренд за',
    'analytics.selectRegions': 'Выбрать регионы',
    'analytics.compareRegions': 'Сравнить регионы',
    'analytics.maxRegions': 'Максимум 10 регионов одновременно',
    'analytics.highestGrowth': 'Самый высокий рост',
    'analytics.biggestDecline': 'Самое большое снижение',
    'analytics.dataPoints': 'точек',
    'analytics.historyData': 'История цен',
    
    'compare.byZones': 'По округам',
    'compare.byRegions': 'По регионам',
    'compare.zoneComparison': 'Сравнение тарифов по федеральным округам',
    'compare.avgPrice': 'Средняя цена',
    'compare.byDistricts': 'По округам',
    'compare.comparison': 'Сравнение тарифов по федеральным округам',
    'compare.mostExpensive': 'Самые дорогие регионы',
    'compare.cheapest': 'Самые дешевые регионы',
    
    'filters.title': 'Фильтры и настройки',
    'filters.zones': 'Федеральные округа',
    'filters.selectAll': 'Выбрать все',
    'filters.deselectAll': 'Сбросить все',
    'filters.tariffType': 'Тип тарифа',
    'filters.all': 'Все',
    'filters.growing': 'Растущие',
    'filters.decreasing': 'Снижающиеся',
    'filters.stable': 'Стабильные',
    'filters.priceRange': 'Диапазон цен',
    'filters.period': 'Период анализа',
    'filters.reset': 'Сбросить фильтры',
    'filters.search': 'Поиск по названию',
    'filters.enterRegion': 'Введите название региона...',
    'filters.federalDistricts': 'Федеральные округа',
    'filters.allRegions': 'Все регионы',
    'filters.risingTariffs': 'Растущие тарифы',
    'filters.decliningTariffs': 'Снижающиеся тарифы',
    'filters.stableTariffs': 'Стабильные тарифы',
    'filters.tariffStructure': 'Структура тарифа',
    'filters.timeZone': 'Временная зона',
    'filters.consumerType': 'Тип потребителя',
    'filters.allConsumers': 'Все потребители',
    'filters.periodAnalysis': 'Период анализа',
    'filters.changeType': 'Тип изменения тарифа',
    
    'common.loading': 'Загрузка данных...',
    'common.price': 'Цена',
    'common.change': 'Изменение',
    'common.region': 'Регион',
    'common.zone': 'Федеральный округ',
    'common.population': 'Население',
    'common.date': 'Дата',
    'common.strength': 'Сила',
    
    'tariff.day': 'День',
    'tariff.night': 'Ночь',
    'tariff.peak': 'Пик',
    'tariff.halfPeak': 'Полупик',
    'tariff.price': 'Цена',
    'tariff.displayMode': 'Режим отображения:',
    'tariff.average': 'Средняя цена',
    'tariff.byZones': 'По зонам',
    'tariff.averageInfo': 'Показана средняя цена по всем тарифным зонам',
    'tariff.zonesInfo': 'Показаны все тарифные зоны отдельно',
    'tariff.single': 'Одноставочный',
    'tariff.twoZone': 'Двухзонный',
    'tariff.threeZone': 'Трёхзонный',
    'tariff.withStove': 'с электроплитой',
    'tariff.standard': 'стандарт',
    'tariff.allTariffs': 'все тарифы',
    
    'timeZone.all': 'Все зоны',
    
    'period.oneMonth': '1 месяц',
    'period.threeMonths': '3 месяца',
    'period.sixMonths': '6 месяцев',
    'period.oneYear': '1 год',
    'period.twoYears': '2 года',
    'period.threeYears': '3 года',
    'period.fiveYears': '5 лет',
    'period.all': 'Все данные',
    
    'sync.copied': 'Скопировано в буфер обмена',
    'sync.updated': 'Обновлено: {0} тарифов из {1} регионов',
    'sync.error': 'Ошибка при синхронизации тарифов',
    'sync.failed': 'Не удалось синхронизировать данные',
    'sync.syncing': 'Синхронизация...',
    'sync.updateTariffs': 'Обновить тарифы',
    
    'cron.automation': 'Автоматизация',
    'cron.autoUpdate': 'Автоматическое обновление тарифов',
    'cron.setupDescription': 'Настройте ежедневную синхронизацию данных о тарифах на электроэнергию',
    'cron.automationUrl': 'URL для автоматизации',
    'cron.setupOptions': 'Варианты настройки',
    'cron.recommended': 'Рекомендуется',
    'cron.freeService': 'Бесплатный сервис для запуска задач по расписанию',
    'cron.register': 'Зарегистрируйтесь на',
    'cron.createTask': 'Создайте новую задачу',
    'cron.pasteUrl': 'Вставьте URL выше',
    'cron.method': 'Метод',
    'cron.schedule': 'Расписание',
    'cron.copyYaml': 'Скопировать YAML',
    'cron.cronSchedule': 'Расписание Cron',
    'cron.generator': 'Генератор Cron',
    'cron.done': 'Готово',
    'cron.everyDay': 'каждый день в 03:00 UTC',
    'cron.every6Hours': 'каждые 6 часов',
    'cron.everyMonday': 'каждый понедельник в 00:00',
    'cron.firstDay': '1-го числа каждого месяца',
    'cron.alternativeService': 'Альтернативный бесплатный cron-сервис',
    'cron.ifConnected': 'Если проект подключён к GitHub',
    'cron.createFile': 'Создайте файл',
    
    'logs.title': 'Журнал синхронизаций',
    'logs.subtitle': 'История обновлений тарифов из официальных источников',
    'logs.all': 'Все',
    'logs.success': 'Успешные',
    'logs.partial': 'Частичные',
    'logs.failed': 'Ошибки',
    'logs.refresh': 'Обновить',
    'logs.noLogs': 'Нет логов синхронизации',
    'logs.noLogsDesc': 'Запустите синхронизацию для создания первого лога',
    'logs.parsed': 'Спарсено',
    'logs.updated': 'Обновлено',
    'logs.skipped': 'Пропущено',
    'logs.sources': 'Источники данных',
    'logs.errors': 'Ошибки',
    
    'forecast.selectRegion': 'Выберите регион для прогноза',
    'forecast.basedOnHistory': 'Прогнозирование на основе исторических данных',
    'forecast.loading': 'Загрузка данных для прогноза...',
    'forecast.selectForForecast': 'Выберите регион',
    'forecast.tariffType': 'Тип тарифа',
    'forecast.growthForecast': 'Прогноз роста цен',
    'forecast.likelyIncrease': 'Регионы с вероятным повышением',
    
    'notFound.oops': 'Упс! Страница не найдена',
    'notFound.backHome': 'Вернуться на главную',
  },
  en: {
    'app.title': 'Electricity Price Monitor',
    'app.subtitle': 'Live data across all Russian regions',
    'app.updated': 'Last updated',
    
    'stats.avgPrice': 'National Average',
    'stats.maxPrice': 'Highest',
    'stats.minPrice': 'Lowest',
    'stats.regions': 'Regions',
    'stats.tracked': 'tracked',
    'stats.perKwh': 'per kWh',
    
    'tabs.overview': 'Overview',
    'tabs.forecast': 'Forecast',
    'tabs.map': 'Map',
    'tabs.regions': 'Regions',
    'tabs.analytics': 'Analytics',
    'tabs.compare': 'Compare',
    'tabs.filters': 'Filters',
    
    'overview.priceDynamics': 'Price Dynamics by Region',
    'overview.avgPricesByZone': 'Average Prices by Federal District',
    'overview.allRegionsByChange': 'All Regions by Price Change',
    'overview.selectRegion': 'Select region',
    
    'export.button': 'Export',
    'export.excel': 'Excel (.xlsx)',
    'export.csv': 'CSV (.csv)',
    'export.csvSuccess': 'CSV file downloaded successfully',
    'export.excelSuccess': 'Excel file downloaded successfully',
    
    'prediction.title': 'Price Forecast',
    'prediction.selectRegion': 'Select region for forecast',
    'prediction.subtitle': 'Forecasting based on historical data',
    'prediction.insufficientData': 'Insufficient data for forecast',
    'prediction.minDataPoints': 'Minimum 10 data points required',
    'prediction.trend': 'Trend',
    'prediction.modelAccuracy': 'Model Accuracy',
    'prediction.forecastIn': 'Forecast in',
    'prediction.days': 'days',
    'prediction.fromCurrent': 'from current',
    'prediction.actual': 'Actual',
    'prediction.forecast': 'Forecast',
    'prediction.today': 'Today',
    'prediction.highAccuracy': 'High accuracy',
    'prediction.mediumAccuracy': 'Medium accuracy',
    'prediction.lowAccuracy': 'Low accuracy',
    'prediction.aboutTitle': 'About the forecast:',
    'prediction.aboutText': 'Forecast is based on linear regression of historical data. The further into the future, the lower the accuracy. Use forecast as a guide, not absolute value.',
    'prediction.risingTitle': 'Price Growth Forecast',
    'prediction.risingSubtitle': 'Regions with likely increase',
    'prediction.fallingTitle': 'Price Decline Forecast',
    'prediction.fallingSubtitle': 'Regions with likely decrease',
    'prediction.current': 'Current',
    'prediction.howItWorks': 'How does the forecast work?',
    'prediction.method': 'Method:',
    'prediction.methodText': 'Linear regression is used to analyze historical data and identify trends.',
    'prediction.accuracy': 'Accuracy:',
    'prediction.accuracyText': 'Depends on the amount of data and price stability. Forecasts for the next month are usually more accurate than for 3-6 months ahead.',
    'prediction.limitations': 'Limitations:',
    'prediction.limitationsText': 'Forecast does not account for external factors (laws, seasonality, force majeure). Use as a planning guide, not an absolute value.',
    'prediction.period.oneMonth': '1 month',
    'prediction.period.threeMonths': '3 months',
    'prediction.period.sixMonths': '6 months',
    'prediction.period.oneYear': '1 year',
    'prediction.period.twoYears': '2 years',
    'prediction.period.threeYears': '3 years',
    'prediction.strength': 'Strength',
    'prediction.actualPrice': 'Actual price',
    'prediction.confidence.high': 'High accuracy',
    'prediction.confidence.medium': 'Medium accuracy',
    'prediction.confidence.low': 'Low accuracy',
    'prediction.veryHighAccuracy': 'Very high accuracy',
    
    'trend.stable': 'Prices are stable',
    'trend.risingSlightly': 'Prices rising slightly',
    'trend.risingModerately': 'Prices rising moderately',
    'trend.risingNoticeably': 'Prices rising noticeably',
    'trend.risingSignificantly': 'Prices rising significantly',
    'trend.fallingSlightly': 'Prices falling slightly',
    'trend.fallingModerately': 'Prices falling moderately',
    'trend.fallingNoticeably': 'Prices falling noticeably',
    'trend.fallingSignificantly': 'Prices falling significantly',
    
    'regions.all': 'All regions',
    'regions.of': 'of',
    'regions.search': 'Search region...',
    'regions.sorting': 'Sort:',
    'regions.byName': 'By name',
    'regions.byPriceAsc': 'By price ↑',
    'regions.byPriceDesc': 'By price ↓',
    'regions.byChangeAsc': 'By change ↑',
    'regions.byChangeDesc': 'By change ↓',
    'regions.export': 'Export',
    'regions.cheaper': 'Cheaper First',
    'regions.expensive': 'More Expensive',
    'regions.growth': 'Growth',
    'regions.decline': 'Decline',
    'regions.notFound': 'Regions not found',
    'regions.tryAgain': 'Try changing the query',
    'regions.details': 'Region Details',
    'regions.currentPrice': 'Current Price',
    'regions.count': 'regions',
    
    'analytics.historicalData': 'Historical Price Data',
    'analytics.period': 'Period:',
    'analytics.trendFor': 'Trend for',
    'analytics.selectRegions': 'Select regions',
    'analytics.compareRegions': 'Compare regions',
    'analytics.maxRegions': 'Maximum 10 regions at once',
    'analytics.highestGrowth': 'Highest growth',
    'analytics.biggestDecline': 'Biggest decline',
    'analytics.dataPoints': 'points',
    'analytics.historyData': 'Price history',
    
    'compare.byZones': 'By Districts',
    'compare.byRegions': 'By Regions',
    'compare.zoneComparison': 'Tariff Comparison by Federal Districts',
    'compare.avgPrice': 'Average price',
    'compare.byDistricts': 'By Districts',
    'compare.comparison': 'Tariff Comparison by Federal Districts',
    'compare.mostExpensive': 'Most Expensive Regions',
    'compare.cheapest': 'Cheapest Regions',
    
    'filters.title': 'Filters and Settings',
    'filters.zones': 'Federal Districts',
    'filters.selectAll': 'Select all',
    'filters.deselectAll': 'Deselect all',
    'filters.tariffType': 'Tariff type',
    'filters.all': 'All',
    'filters.growing': 'Growing',
    'filters.decreasing': 'Decreasing',
    'filters.stable': 'Stable',
    'filters.priceRange': 'Price range',
    'filters.period': 'Analysis period',
    'filters.reset': 'Reset filters',
    'filters.search': 'Search by name',
    'filters.enterRegion': 'Enter region name...',
    'filters.federalDistricts': 'Federal Districts',
    'filters.allRegions': 'All Regions',
    'filters.risingTariffs': 'Rising Tariffs',
    'filters.decliningTariffs': 'Declining Tariffs',
    'filters.stableTariffs': 'Stable Tariffs',
    'filters.tariffStructure': 'Tariff Structure',
    'filters.timeZone': 'Time Zone',
    'filters.consumerType': 'Consumer Type',
    'filters.allConsumers': 'All Consumers',
    'filters.periodAnalysis': 'Analysis Period',
    'filters.changeType': 'Tariff Change Type',
    
    'common.loading': 'Loading data...',
    'common.price': 'Price',
    'common.change': 'Change',
    'common.region': 'Region',
    'common.zone': 'Federal District',
    'common.population': 'Population',
    'common.date': 'Date',
    'common.strength': 'Strength',
    
    'tariff.day': 'Day',
    'tariff.night': 'Night',
    'tariff.peak': 'Peak',
    'tariff.halfPeak': 'Half-peak',
    'tariff.price': 'Price',
    'tariff.displayMode': 'Display mode:',
    'tariff.average': 'Average price',
    'tariff.byZones': 'By zones',
    'tariff.averageInfo': 'Average price across all tariff zones shown',
    'tariff.zonesInfo': 'All tariff zones shown separately',
    'tariff.single': 'Single Rate',
    'tariff.twoZone': 'Two-Zone',
    'tariff.threeZone': 'Three-Zone',
    'tariff.withStove': 'with electric stove',
    'tariff.standard': 'standard',
    'tariff.allTariffs': 'all tariffs',
    
    'timeZone.all': 'All Zones',
    
    'period.oneMonth': '1 month',
    'period.threeMonths': '3 months',
    'period.sixMonths': '6 months',
    'period.oneYear': '1 year',
    'period.twoYears': '2 years',
    'period.threeYears': '3 years',
    'period.fiveYears': '5 years',
    'period.all': 'All data',
    
    'sync.copied': 'Copied to clipboard',
    'sync.updated': 'Updated: {0} tariffs from {1} regions',
    'sync.error': 'Tariff sync error',
    'sync.failed': 'Failed to sync data',
    'sync.syncing': 'Syncing...',
    'sync.updateTariffs': 'Update Tariffs',
    
    'cron.automation': 'Automation',
    'cron.autoUpdate': 'Automatic Tariff Updates',
    'cron.setupDescription': 'Set up daily synchronization of electricity tariff data',
    'cron.automationUrl': 'Automation URL',
    'cron.setupOptions': 'Setup Options',
    'cron.recommended': 'Recommended',
    'cron.freeService': 'Free service for scheduled tasks',
    'cron.register': 'Register at',
    'cron.createTask': 'Create new task',
    'cron.pasteUrl': 'Paste URL above',
    'cron.method': 'Method',
    'cron.schedule': 'Schedule',
    'cron.copyYaml': 'Copy YAML',
    'cron.cronSchedule': 'Cron Schedule',
    'cron.generator': 'Cron Generator',
    'cron.done': 'Done',
    'cron.everyDay': 'every day at 03:00 UTC',
    'cron.every6Hours': 'every 6 hours',
    'cron.everyMonday': 'every Monday at 00:00',
    'cron.firstDay': '1st of every month',
    'cron.alternativeService': 'Alternative free cron service',
    'cron.ifConnected': 'If project is connected to GitHub',
    'cron.createFile': 'Create file',
    
    'logs.title': 'Synchronization Logs',
    'logs.subtitle': 'History of tariff updates from official sources',
    'logs.all': 'All',
    'logs.success': 'Successful',
    'logs.partial': 'Partial',
    'logs.failed': 'Failed',
    'logs.refresh': 'Refresh',
    'logs.noLogs': 'No sync logs',
    'logs.noLogsDesc': 'Run synchronization to create first log',
    'logs.parsed': 'Parsed',
    'logs.updated': 'Updated',
    'logs.skipped': 'Skipped',
    'logs.sources': 'Data Sources',
    'logs.errors': 'Errors',
    
    'forecast.selectRegion': 'Select region for forecast',
    'forecast.basedOnHistory': 'Forecasting based on historical data',
    'forecast.loading': 'Loading forecast data...',
    'forecast.selectForForecast': 'Select Region',
    'forecast.tariffType': 'Tariff Type',
    'forecast.growthForecast': 'Price Growth Forecast',
    'forecast.likelyIncrease': 'Regions with likely increase',
    
    'notFound.oops': 'Oops! Page not found',
    'notFound.backHome': 'Back to home',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'ru') ? saved : 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}